# Site settings
title: Scott Newson
description: Personal website.
url: http://scottnewson.ca

# Build settings
markdown: kramdown
exclude: 
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
sass:
  style: compressed
