# Site settings
title: Scott Newson
description: Personal website.

# Build settings
markdown: kramdown
exclude: 
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
sass:
  style: compressed
